<?php

/**
 * This is the model base class for the table "questionary".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Questionary".
 *
 * Columns in table "questionary" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $question
 * @property integer $order
 * @property string $answer
 *
 */
abstract class BaseQuestionary extends GxActiveRecord {

	public $created_log_field = 'created_at';

	public $updated_log_field = 'updated_at';

	public $user_update_log_field = 'user_update_id';
	

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'questionary';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Questionary|Questionaries', $n);
	}

	public static function representingColumn() {
		return 'question';
	}

	public function rules() {
		return array(
			array('order', 'numerical', 'integerOnly'=>true),
			array('answer', 'length', 'max'=>255),
			array('question', 'safe'),
			array('question, order, answer', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, question, order, answer', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'question' => Yii::t('app', 'Question'),
			'order' => Yii::t('app', 'Order'),
			'answer' => Yii::t('app', 'Answer'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('t.id', $this->id, true);
		$criteria->compare('t.question', $this->question, true);
		$criteria->compare('t.order', $this->order);
		$criteria->compare('t.answer', $this->answer, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}

	/**
	*	Autolog some fields if exists
	*
	*
	*/
	public function behaviors()
	{
    	return array(
        	'AutoLogBehavior' => array(
            	'class' => 'application.components.AutoLogBehavior',
            	//You can optionally set the field name options here
        	)
    	);
	}
}