<?php

/**
 * This is the model base class for the table "price_list".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PriceList".
 *
 * Columns in table "price_list" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $brand
 * @property string $model
 * @property string $locked_price
 * @property string $unlocked_price
 * @property string $broken_price
 * @property string $created_at
 * @property string $updated_at
 * @property string $user_update_id
 *
 */
abstract class BasePriceList extends GxActiveRecord {

	public $created_log_field = 'created_at';

	public $updated_log_field = 'updated_at';

	public $user_update_log_field = 'user_update_id';
	

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'price_list';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PriceList|PriceLists', $n);
	}

	public static function representingColumn() {
		return 'brand';
	}

	public function rules() {
		return array(
			array('brand, model', 'required'),
			array('brand, model', 'length', 'max'=>255),
			array('locked_price, unlocked_price, broken_price', 'length', 'max'=>8),
			array('user_update_id', 'length', 'max'=>10),
			array('created_at, updated_at', 'safe'),
			array('locked_price, unlocked_price, broken_price, created_at, updated_at, user_update_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, brand, model, locked_price, unlocked_price, broken_price, created_at, updated_at, user_update_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'brand' => Yii::t('app', 'Brand'),
			'model' => Yii::t('app', 'Model'),
			'locked_price' => Yii::t('app', 'Locked Price'),
			'unlocked_price' => Yii::t('app', 'Unlocked Price'),
			'broken_price' => Yii::t('app', 'Broken Price'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'user_update_id' => Yii::t('app', 'User Update'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('brand', $this->brand, true);
		$criteria->compare('model', $this->model, true);
		$criteria->compare('locked_price', $this->locked_price, true);
		$criteria->compare('unlocked_price', $this->unlocked_price, true);
		$criteria->compare('broken_price', $this->broken_price, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('user_update_id', $this->user_update_id, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}

	/**
	*	Autolog some fields if exists
	*
	*
	*/
	public function behaviors()
	{
    	return array(
        	'AutoLogBehavior' => array(
            	'class' => 'application.components.AutoLogBehavior',
            	//You can optionally set the field name options here
        	)
    	);
	}
}