<?php
/**
 *  Copyright 2015 Reverb Technologies, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 */

class FecaedetRequest
{
    static $swaggerTypes = array(
      'iva' => 'iva',
      'concepto' => 'int',
      'docTipo' => 'int',
      'docNro' => 'int',
      'cbteDesde' => 'int',
      'cbteHasta' => 'int',
      'cbteFch' => 'string',
      'impTotal' => 'double',
      'impTotConc' => 'double',
      'impNeto' => 'double',
      'impOpEx' => 'double',
      'impTrib' => 'double',
      'impIVA' => 'double',
      'fchServDesde' => 'string',
      'fchServHasta' => 'string',
      'fchVtoPago' => 'string',
      'monCotiz' => 'double',
      'cbtesAsoc' => 'cbtesAsoc',
      'tributos' => 'tributos',
      'opcionales' => 'opcionales',
      'monId' => 'string'
    );

  
    public $iva; /* iva */
    public $concepto; /* int */
    public $docTipo; /* int */
    public $docNro; /* int */
    public $cbteDesde; /* int */
    public $cbteHasta; /* int */
    public $cbteFch; /* string */
    public $impTotal; /* double */
    public $impTotConc; /* double */
    public $impNeto; /* double */
    public $impOpEx; /* double */
    public $impTrib; /* double */
    public $impIVA; /* double */
    public $fchServDesde; /* string */
    public $fchServHasta; /* string */
    public $fchVtoPago; /* string */
    public $monCotiz; /* double */
    public $cbtesAsoc; /* cbtesAsoc */
    public $tributos; /* tributos */
    public $opcionales; /* opcionales */
    public $monId; /* string */
}
