<?php
/**
 *  Copyright 2015 Reverb Technologies, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 */

class FecaedetResponse
{
    static $swaggerTypes = array(
      'concepto' => 'int',
      'docTipo' => 'int',
      'docNro' => 'int',
      'cbteDesde' => 'int',
      'cbteHasta' => 'int',
      'cbteFch' => 'string',
      'cae' => 'string',
      'caefchVto' => 'string',
      'observaciones' => 'observaciones',
      'resultado' => 'string'
    );

  
    public $concepto; /* int */
    public $docTipo; /* int */
    public $docNro; /* int */
    public $cbteDesde; /* int */
    public $cbteHasta; /* int */
    public $cbteFch; /* string */
    public $cae; /* string */
    public $caefchVto; /* string */
    public $observaciones; /* observaciones */
    public $resultado; /* string */
}
