<p style="font-size:7pt;">
<span style="font-size:10pt; font-weight:bold;">Condiciones Generales</span>
<br/><br/>
PRIMERA. Mediante la suscripción del presente, el firmante procede a la venta a BGH S.A. con domicilio en la calle Brasil 731, Ciudad Autónoma de Buenos Aires (en adelante "BGH"), de los productos que se entregan en el punto de venta identificado en el presente documento (en adelante el/los "Punto/s de Venta"). Se deja expresa constancia que el Punto de Venta actúa como intermediario entre el cliente y BGH (en adelante "Contenido de la Operación").
<br/><br/>
SEGUNDA. BGH abonará el precio de venta acordado e indicado en el presente documento en el cuadro "Contenido de la Venta" (en adelante el "Importe") mediante el envío a la dirección de correo electrónico informada, de un/a voucher por el Importe dentro de las 96 hs de suscripto el presente, sirviendo éste documento como aceptación y conocimiento de los términos de utilización del mismo (en adelante el "Voucher"). La mera suscripción del presente documento por parte de cliente implicará su pleno conocimiento y aceptación respecto de los términos y utilidad del Voucher. Se deja expresa constancia que en ningún caso (i) el Voucher será reemplazado en caso de extravío, (ii) BGH abonará el Importe en dinero en efectivo y (iii) el Voucher será canjeado por dinero.
<br/><br/>
TERCERA. Los productos serán calificados con los términos "FUNCIONA" y "NO FUNCIONA" en los Puntos de Venta. Los productos: (i) a los que al incorporarse su batería puedan encenderse y apagarse, (ii) su pantalla LCD se encuentre intacta y/o su funcionamiento sea correcto y (iii) la pantalla táctil no se encuentre dañada (únicamente para smartphones: teléfonos inteligentes), serán calificados con el término "FUNCIONA". En caso contrario, el/los producto/s será/n calificado/s como "NO FUNCIONA".
<br/><br/>
CUARTA. El firmante declara que es único propietario de los productos incluidos en la orden de venta y manifiesta ser mayor de 18 años. El firmante asume toda responsabilidad derivada de la venta de los productos entregados en el Punto de Venta.
<br/>
Asimismo, se deja expresa constancia que es responsabilidad del firmante previo a la entrega del producto en el Punto de Venta, (i) extraer las correspondientes tarjetas SIM a todos los productos incluidos en la venta y (ii) proceder al borrado de todos los datos que contengan los productos, ya sea información personal, mensajes de texto, fotos, juegos, canciones y/o cualquier otra información de carácter personal. En tal sentido, el firmante autoriza expresamente a BGH a eliminar de forma permanente toda la información que pudiera contener el/los productos objeto del presente, y exime a BGH de toda responsabilidad por pérdida o daño de los datos grabados o contenidos en los productos.
<br/>
Ni BGH ni el Punto de Venta serán responsables del costo, pago y cualquier otra consecuencia legal de ninguna comunicación efectuada antes y/o después de la entrega de los productos por parte del cliente.
<br/>
El Cliente es responsable de la veracidad de los datos aportados, asumiendo cualquier responsabilidad derivada de la inexactitud de los mismos.
<br/><br/>
QUINTA. La operación de referencia requiere el tratamiento por parte de BGH y/o los Puntos de Venta de los datos personales solicitados al firmante. Estos datos serán administrados de acuerdo a lo establecido en la normativa vigente en materia de protección de datos de carácter personal.
<br/>
En este sentido, aquellos datos del solicitante que no requieren su consentimiento previo para su recolección, tratamiento y cesión -conforme con lo establecido en los artículos 5º, inciso 2., sub-inciso c), y 11º, de la Ley N° 25.326 de Protección de Datos Personales-, podrán ser utilizados por BGH, o por terceras personas a las que BGH se los hubiere cedido, para la realización de acciones promocionales de marketing, sin necesidad de notificación y/o autorización previa del cliente. En caso que el cliente quisiere tener conocimiento de la identificación y datos del cesionario de los archivos cedidos, deberá solicitarlo a BGH por medio fehaciente, o personalmente, en los Centros de Atención al Cliente.
<br/>
Los datos personales suministrados en el mencionado formulario serán incluidos en archivos automatizados, procesados bajo normas de estricta confidencialidad y protección de datos. Los datos personales serán utilizados por BGH con el objeto de brindar y mejorar la oferta de productos móviles a sus clientes y podrá ser utilizado para acciones promocionales de marketing y/o fines estadísticos. Los titulares de los datos personales podrán, en cualquier momento, ejercer su derecho a acceder, rectificar, actualizar, cancelar y/o suprimir dichos datos, de conformidad a lo previsto en la Ley 25.326 y su Decreto Reglamentario 1558/2001, por medio de nota o presentación escrita con firma certificada, medio postal o telegráfico y/o carta documento acreditando fehacientemente su identidad en Brasil N° 731 CP 1154, Ciudad Autónoma de Buenos Aires. El titular de los datos personales tiene la facultad de ejercer el derecho de acceso a los mismos en forma gratuita a intervalos no inferiores a seis meses, salvo que se acredite un interés legítimo al efecto conforme lo establecido en el artículo 14, inciso 3 de la Ley Nº 25.326. La DIRECCION NACIONAL DE PROTECCION DE DATOS PERSONALES, Órgano de Control de la Ley Nº 25.326, tiene la atribución de atender las denuncias y reclamos que se interpongan con relación al incumplimiento de las normas sobre protección de datos personales.
<br/><br/>
SEXTA. Las presentes condiciones generales y operación comercial se regirán por la ley de la República Argentina, y cualquier reclamo que pudiera suscitarse en el marco de la presente deberá ser sometido a la competencia de la justicia nacional en lo comercial con asiento en la Ciudad Autónoma de Buenos Aires.
<br/><br/>
SÉPTIMA. BGH se reserva el derecho a resolver la presente relación comercial en caso de incumplimiento por parte del firmante de cualquiera de los términos y condiciones establecidos en las presentes condiciones generales.
</p>